(function() {var implementors = {};
implementors["show_notes"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"show_notes/e002/struct.Circle.html\" title=\"struct show_notes::e002::Circle\">Circle</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"show_notes/e003/struct.PreexistingStruct.html\" title=\"struct show_notes::e003::PreexistingStruct\">PreexistingStruct</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"show_notes/e003/enum.RelatedishThings.html\" title=\"enum show_notes::e003::RelatedishThings\">RelatedishThings</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"show_notes/e009/struct.DoubleAndOne.html\" title=\"struct show_notes::e009::DoubleAndOne\">DoubleAndOne</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"show_notes/e019/struct.A_NoCopyOrClonePoint.html\" title=\"struct show_notes::e019::A_NoCopyOrClonePoint\">A_NoCopyOrClonePoint</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"show_notes/e019/struct.B_JustClonePoint.html\" title=\"struct show_notes::e019::B_JustClonePoint\">B_JustClonePoint</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"show_notes/e019/struct.C_CopyPoint.html\" title=\"struct show_notes::e019::C_CopyPoint\">C_CopyPoint</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
